package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"github.com/quant-risk/radiant-harness/internal/config"
	"github.com/quant-risk/radiant-harness/internal/mode"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

func registerModeCmd(root *cobra.Command) {
	modeCmd := &cobra.Command{
		Use:   "mode",
		Short: "Show or set the operational mode (light|full|auto)",
		Long: `The harness operates in one of two modes:

  light — harness possesses the agent via MCP sampling. The host agent
          (Claude Code, Cursor, Hermes, ...) performs LLM inference with
          its own credentials. No API key required.

  full  — harness is autonomous. The harness calls LLM HTTP endpoints
          directly (OpenRouter, OpenAI, Anthropic, ...). Requires an
          API key in the environment or .radiant.yaml.

Resolution chain (highest priority first):
  1. --mode flag
  2. RADIANT_MODE env var
  3. .radiant.yaml → mode:
  4. auto-detect (MCP config found → light; API key found → full; else light)

Examples:
  radiant mode show
  radiant mode set light
  radiant mode set full
  radiant mode set auto`,
	}

	var jsonOut bool
	showCmd := &cobra.Command{
		Use:   "show",
		Short: "Show the resolved mode and where it came from",
		RunE: func(cmd *cobra.Command, _ []string) error {
			cwd, _ := os.Getwd()
			cfg, _ := config.Load(cwd)
			modeCfg := ""
			if cfg != nil {
				modeCfg = cfg.Mode
			}
			r := mode.Resolve("", cwd, modeCfg)
			if jsonOut {
				out := struct {
					Mode   string `json:"mode"`
					Source string `json:"source"`
					Reason string `json:"reason"`
				}{
					Mode:   r.Mode.String(),
					Source: string(r.Source),
					Reason: r.Reason,
				}
				b, _ := json.MarshalIndent(out, "", "  ")
				fmt.Println(string(b))
				return nil
			}
			fmt.Printf("Mode:    %s\n", r.Mode)
			fmt.Printf("Source:  %s\n", r.Source)
			fmt.Printf("Reason:  %s\n", r.Reason)
			fmt.Println()
			fmt.Printf("  light — %s\n", mode.Light.Description())
			fmt.Printf("  full  — %s\n", mode.Full.Description())
			return nil
		},
	}
	showCmd.Flags().BoolVar(&jsonOut, "json", false, "emit JSON instead of human text")
	modeCmd.AddCommand(showCmd)

	setCmd := &cobra.Command{
		Use:   "set <light|full|auto>",
		Short: "Persist the default mode in .radiant.yaml",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			m, err := mode.Parse(args[0])
			if err != nil {
				return err
			}
			if m == mode.Auto {
				return fmt.Errorf("cannot persist 'auto' — pick light or full. Use 'unset' to remove the field.")
			}
			cwd, _ := os.Getwd()
			if err := writeModeToRadiantYAML(cwd, m.String()); err != nil {
				return err
			}
			fmt.Printf("✓ Mode set to %s in .radiant.yaml\n", m)
			fmt.Printf("  (RADIANT_MODE env var or --mode flag still override this)\n")
			return nil
		},
	}
	modeCmd.AddCommand(setCmd)

	root.AddCommand(modeCmd)
}

// writeModeToRadiantYAML sets `mode: <value>` in the project's .radiant.yaml.
// If the file exists, we update it in place (preserving other fields). If it
// doesn't, we create a minimal one. We touch only the mode field — all other
// config is left untouched.
func writeModeToRadiantYAML(projectDir, value string) error {
	path := filepath.Join(projectDir, ".radiant.yaml")
	data := make(map[string]interface{})

	if existing, err := os.ReadFile(path); err == nil {
		_ = yaml.Unmarshal(existing, &data)
	}
	data["mode"] = value

	out, err := yaml.Marshal(data)
	if err != nil {
		return fmt.Errorf("marshal yaml: %w", err)
	}
	header := "# radiant-harness project config\n# generated by `radiant mode set`\n"
	return os.WriteFile(path, []byte(header+string(out)), 0o644)
}