#!/usr/bin/env bash
# scripts/run.sh — entrypoint for spec 0001-remover-a-spec-menuflex-do-reposit-rio-porque-pertence-a-outro-c
#
# Generated by radiant-harness self-driven mode (v3.6.0+).
# Verify that the unrelated MenuFlex case is no longer present outside this audit trail.

set -euo pipefail
cd "$(dirname "$0")/.."

if git grep -i -n "menuflex" -- . \
  ':!docs/README.md' \
  ':!scripts/run.sh' \
  ':!specs/0001-remover-a-spec-menuflex-do-reposit-rio-porque-pertence-a-outro-c/spec.md' \
  ':!specs/0001-remover-a-spec-menuflex-do-reposit-rio-porque-pertence-a-outro-c/tasks.md'; then
  echo "[radiant] MenuFlex references still exist outside the cleanup audit trail." >&2
  exit 1
fi

echo "[radiant] MenuFlex cleanup verified."
